Robots:
- robot_name: "vaultbot_sim"
  description: "NRG vaultbot simulation"
  reliability: 0.8
  urdf:
    package_name: "husky_dual_ur5_description"
    executable: "urdf/husky_dual_ur5.urdf.xacro"
  navigation:
    controller:
      package_name: "husky_dual_ur5_config"
      executable: "husky_dual_ur5_nav_controller.launch"
      global_planner: "navfn/NavfnROS"
      local_planner: "base_local_planner/TrajectoryPlannerROS"
      scan_topic: "scan"
      pose_topic: "amcl_pose"
    driver:
      package_name: "husky_dual_ur5_config" 
      executable: "husky_dual_ur5_nav_driver.launch"
      odom_topic: "odometry/filtered"
      cmd_vel_topic: "cmd_vel"
  manipulation:
    controller:
      package_name: "husky_dual_ur5_config" 
      executable: "husky_dual_ur5_manip_controller.launch"
      args: "debug:=false"
      planning_groups: ["l_arm", "r_arm"]
    driver:
      package_name: "husky_dual_ur5_config" 
      executable: "husky_dual_ur5_manip_driver.launch"